### PR TITLE
Handle DTMFs in iOS

### PR DESCRIPTION
**Pull request by nickmendes**
- Added DTMF action event
- Added enable/disable DTMF usage

### CODE REVIEW

**Comment by dmarcs** [comment]
@liberatomota-itcenter @nickmendes This is a great addition to the plugin! I tested your code, and it works well. It looks like it's possible to handle DTMFs in Android also, so I'll try to add that when I get a chance. I can't see why someone would want to implement DTMF handling in a VOIP app, but it's pretty cool that you can capture number presses in the middle of a call. Thanks for the PR 😃

**Comment by nickmendes** [comment]
Thanks for your input, we will be contributing again shortly with dual call handling and some other nice things. 
As you said it's not usual to use DTMF in voIP apps, but we need it to for eg: merge calls with each other, to join conferences, etc ...
If one doesn't want to use DTMF we made an option where you can disable DTMF's in Callkit view, better to disable it than to have it enable and not working :D
Always good to give back to the community 👍

**Comment by dmarcs** [comment]
Awesome! Getting dual call handling to work is not easy. Now I understand why you would want to use DTMF. It makes sense for multi-party calls, so you can press #1 for example and join a conference.

**Comment by amuzacz** [comment]
Here is how you can add this to android: https://github.com/VoIPstudio/CordovaCall/commit/6a81aa9c0d04c4891496f815c8e04f4588b41bb2#diff-c7d690b77759ec1572eb0707d9333651R98

**Pull request merged**
